$ PURGE
$!
$ LOG_FILES = F$SEARCH("*.LOG;*")
$ IF LOG_FILES .NES. ""
$ THEN
$   DELETE *.LOG;*
$ ENDIF
$!
$ OUT_FILES = F$SEARCH("*.OUT;*")
$ IF OUT_FILES .NES. ""
$ THEN
$   DELETE *.OUT;*
$ ENDIF
$!
$ OUT_FILES = F$SEARCH("*.TXT;*")
$ IF OUT_FILES .NES. ""
$ THEN
$   DELETE *.TXT;*
$ ENDIF
$!
$ TEST_FOLDER = F$SEARCH("TEST.DIR;1")
$ IF TEST_FOLDER .NES. ""
$ THEN
$   DELETE/TREE [.TEST...]*.*;*
$   SET FILE/PROT=O:D TEST.DIR
$   DELETE TEST.DIR;
$ ENDIF
