$ OUT_DIR = f$trnlnm("GITTEST$ROOT","LNM$PROCESS_TABLE")
$
$ LOG_FILES = F$SEARCH("*.LOG;*")
$ IF LOG_FILES .NES. ""
$ THEN
$     Dele *.LOG;*
$ ENDIF
$
$ OUT_FILES = F$SEARCH("*.OUT;*")
$ IF OUT_FILES .NES. ""
$ THEN
$     Dele *.OUT;*
$ ENDIF
$
$ OUT_FILES = F$SEARCH("*GIT_INIT_SEPARATE.EXP;*")
$ IF OUT_FILES .NES. ""
$ THEN
$     Dele GIT_INIT_SEPARATE.EXP;*
$ ENDIF
$
$ test_FOLDER = F$SEARCH("TEST.DIR;*")
$ IF test_FOLDER .NES. ""
$ THEN
$     @'OUT_DIR'REMOVE_DIR TEST
$ ENDIF
$
$ OUT_FILES = F$SEARCH("*.OBJ;*")
$ IF OUT_FILES .NES. ""
$ THEN
$     Dele *.OBJ;*
$ ENDIF
$
$ OUT_FILES = F$SEARCH("*.EXE;*")
$ IF OUT_FILES .NES. ""
$ THEN
$     Dele *.EXE;*
$ ENDIF
