$ OUT_DIR = f$trnlnm("GITTEST$ROOT","LNM$PROCESS_TABLE")
$!
$ LOG_FILES = F$SEARCH("*.LOG;*")
$ IF LOG_FILES .NES. ""
$ THEN
$   DELETE *.LOG;*
$ ENDIF
$!
$ OUT_FILES = F$SEARCH("*.OUT;*")
$ IF OUT_FILES .NES. ""
$ THEN
$   DELETE *.OUT;*
$ ENDIF
$!
$ OUT_FILES = F$SEARCH("*GIT_INIT_SEPARATE.EXP;*")
$ IF OUT_FILES .NES. ""
$ THEN
$   DELETE GIT_INIT_SEPARATE.EXP;*
$ ENDIF
$!
$ TEST_FOLDER = F$SEARCH("TEST.DIR;*")
$ IF TEST_FOLDER .NES. ""
$ THEN
$   @'OUT_DIR'REMOVE_DIR TEST
$ ENDIF
$!
$ OUT_FILES = F$SEARCH("*.OBJ;*")
$ IF OUT_FILES .NES. ""
$ THEN
$   DELETE *.OBJ;*
$ ENDIF
$!
$ OUT_FILES = F$SEARCH("*.EXE;*")
$ IF OUT_FILES .NES. ""
$ THEN
$   DELETE *.EXE;*
$ ENDIF
