$ PURGE
$ OUT_DIR = f$trnlnm("GITTEST$ROOT","LNM$PROCESS_TABLE")
$!
$ LOG_FILES = F$SEARCH("*.LOG;*")
$ IF LOG_FILES .NES. ""
$ THEN
$   DELETE *.LOG;*
$ ENDIF
$!
$ OUT_FILES = F$SEARCH("*.OUT;*")
$ IF OUT_FILES .NES. ""
$ THEN
$   DELETE *.OUT;*
$ ENDIF
$!
$ TEST_FOLDER = F$SEARCH("TEST.DIR;1")
$ IF TEST_FOLDER .NES. ""
$ THEN
$   @'OUT_DIR'REMOVE_DIR TEST
$ ENDIF
$!
$ TEST_NAME = "GIT_BISECT_GOOD_BAD_LOG"
$ OUT_FILES = F$SEARCH("''TEST_NAME'.EXP;*")
$ IF OUT_FILES .NES. ""
$ THEN
$   DELETE 'TEST_NAME'.EXP;*
$   CREATE 'TEST_NAME'.EXP;1
$ ENDIF
