#!/bin/sh
# Copyright (C) 2025 VMS Software, Inc.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation version 2 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see https://www.gnu.org/licenses/

die () {
	echo "$@" >&2
	exit 1
}

command_list () {
	while read cmd rest
	do
		case "$cmd" in
		"#"* | '')
			# Ignore comments and allow empty lines
			continue
			;;
		*)
			case "$exclude_programs" in
			*":$cmd:"*)
				;;
			*)
				echo "$cmd $rest"
				;;
			esac
		esac
	done <"$1"
}

category_list () {
	echo "$1" |
	cut -d' ' -f2- |
	tr ' ' '\012' |
	grep -v '^$' |
	LC_ALL=C sort -u
}

define_categories () {
	echo
	echo "/* Command categories */"
	bit=0

#	On OpenVMS split the text by spaces and then process as there is an issue with the length of string
	if [ "$2" = "OpenVMS" ]; then
		chunk=""
		for word in $1; do
			chunk+=" $word"
			if [[ $chunk == *" "* ]]; then
				echo "$chunk" |
				while read cat
				do
					echo "#define CAT_$cat (1UL << $bit)"
				done
				chunk=""
			fi
			bit=$(($bit+1))
		done
	else
		echo "$1" |
		while read cat
		do
			echo "#define CAT_$cat (1UL << $bit)"
			bit=$(($bit+1))
		done
	fi
	test "$bit" -gt 32 && die "Urgh.. too many categories?"
}

define_category_names () {
	echo
	echo "/* Category names */"
	echo "static const char *category_names[] = {"
	bit=0
#	On OpenVMS process by chunks as there is issue with the length of string
	if [ "$2" = "OpenVMS" ]; then
		chunk=""
		for word in $1; do
			chunk+=" $word"
			if [[ $chunk == *" "* ]]; then
				echo "$chunk" |
				while read cat
				do
					echo "	\"$cat\", /* (1UL << $bit) */"
					bit=$(($bit+1))
				done
				chunk=""
			fi
			bit=$(($bit+1))
		done
	else
		echo "$1" |
		while read cat
		do
			echo "	\"$cat\", /* (1UL << $bit) */"
			bit=$(($bit+1))
		done
	fi
	echo "	NULL"
	echo "};"
}

print_command_list () {
	echo "static struct cmdname_help command_list[] = {"

	if [ "$2" = "OpenVMS" ]; then
		while read line; do
			cmd="${line%% *}"
			rest="${line#* }" 

			synopsis=
			while read line
			do
				case "$line" in
				"$cmd - "*)
					synopsis=${line#$cmd - }
					break
					;;
				esac
			done <"../Documentation/$cmd.txt"

			printf '\t{ "%s", N_("%s"), 0' "$cmd" "$synopsis"
			printf " | CAT_%s" $rest
			echo " },"

		done <<< "$1"
	else
		echo "$1" |
		while read cmd rest
		do
			synopsis=
			while read line
			do
				case "$line" in
				"$cmd - "*)
					synopsis=${line#$cmd - }
					break
					;;
				esac
			done <"../Documentation/$cmd.txt"

			printf '\t{ "%s", N_("%s"), 0' "$cmd" "$synopsis"
			printf " | CAT_%s" $rest
			echo " },"
		done
	fi
	echo "};"
}

exclude_programs=:
while test "--exclude-program" = "$1"
do
	shift
	exclude_programs="$exclude_programs$1:"
	shift
done

commands="$(command_list "$1")"
categories="$(category_list "$commands")"

echo "/* Automatically generated by generate-cmdlist.sh */
struct cmdname_help {
	const char *name;
	const char *help;
	uint32_t category;
};
"
define_categories "$categories" "$2"
echo
define_category_names "$categories" "$2"
echo
print_command_list "$commands" "$2"
