On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   test_file_1.txt
	new file:   test_file_2.txt
	new file:   test_file_4.txt

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   test_file_1.txt
	deleted:    test_file_4.txt

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	test_file_3.txt

